### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by gustawdaniel** [ilyapt/facebook-nologin-scraper#11]
Hi @ilyapt. I finished roadmap from #5 and created version `0.2.0`.
Please for your review and critical comments.

There is next roadmap for version `0.3.0`

- [ ] add changelog
- [ ] add eslint https://eslint.org/docs/user-guide/getting-started
- [ ] remove ts-ignore from source code
- [ ] create documentation of interfaces for organizations and private profiles
- [ ] decide if we want to use puppeter and proxies inside of this package #8, #2 
- [ ] create video tutorial introducing for new users #3

I think most important discussion is on issue #8 because of I propose approach:

- slim, solid, well tested and documented package

but we have also pull request from @mihailShumilov that propose:

- ready for use with proxy from console, automatily scrolling

**Comment by gustawdaniel** [comment]
EsLint rules:

```
✔ How would you like to use ESLint? · style
✔ What type of modules does your project use? · esm
✔ Which framework does your project use? · none
✔ Does your project use TypeScript? · No / Yes
✔ Where does your code run? · node
✔ How would you like to define a style for your project? · prompt
✔ What format do you want your config file to be in? · JSON
✔ What style of indentation do you use? · 4
✔ What quotes do you use for strings? · single
✔ What line endings do you use? · unix
✔ Do you require semicolons? · No / Yes
```
